on:
  release:
    types: 
      - released
      - prereleased

jobs:
  build:
    name: Build and Publish Nuget Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Set our prerelease number if needed
      if: ${{ github.event.action == 'prereleased' }}
      run: echo "PRERELEASE_ARG='--version-suffix $GITHUB_RUN_NUMBER'" >> $GITHUB_ENV
    - name: Get version from tag name
      run: echo "VERSION_NUMBER=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV
    - uses: actions/checkout@v3.3.0
    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.x
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 6.4.x
    - name: Dotnet Restore
      run: dotnet restore
    - name: Dotnet Build
      run: dotnet build --no-restore --configuration release
    - name: Dotnet Pack
      run: dotnet pack src/QuikBlazor.HttpValues --configuration release -o packages /p:Version=${{ env.VERSION_NUMBER }} ${{ env.PRERELEASE_ARG }}
    - name: Nuget push
      run: dotnet nuget push "packages/*.nupgk" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      